<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="Content-Style-Type" content="text/css"/>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
</head>
<body>
<div id="wrapper">
    <div id="header">
        <a href="/">Главная</a> /
        <a href="/register">Регистрация</a> /
        <a href="/account">Личный кабинет</a>
    </div>
    <div id="content">
        <?php include 'app/views/' . $content_view; ?>
    </div>
    <div id="footer"> @copyright 2017</div>
</div>
</body>
</html>
